### PR TITLE
Remove typo

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
I'm surprised that compiles?

### CODE REVIEW

**Comment by ViralBShah** [comment]
```
julia> function f(a,b)\
           return a+b
           end
f (generic function with 1 method)

julia> f(2,3)
5
```

The parser accepts it.

**Comment by ChrisRackauckas** [comment]
That's still kind of odd though. I would've assumed it would just error. I feel like next JuliaCon we should have random Julia trivia like this.

**Comment by ViralBShah** [comment]
Jameson said it is not a typo and actually valid syntax.

**Comment by ChrisRackauckas** [comment]
It's valid, but you still probably don't want to do this. It's just like:

```julia
function f(a,b)
  2
  a+b
end
```

you might as well delete the `2`. It's kind of interesting that it parses like that though, since

```julia
function f(a,b)
  \
  a+b
end
```

yeah I guess it's okay and it'll ignore the `\`. The fact that it should work though is obscure enough Julia trivia that I would assume you wouldn't want it in a package.

**Pull request merged**
